### ISSUE TITLE
[Bug] Getting this Crash with BClib when using Biolith 

### ISSUE THREAD

**Issue by Daihok41** [quiqueck/BCLib#101] opened 2023-06-17 23:12 UTC
### What happened?

As soon as it trys to load world it saves and crashs. This is just with bclib without better nether or better end.  https://pastebin.com/rVTeBT49

### BCLib

3.0.7

### Fabric API

0.83.1

### Fabric Loader

0.14.21

### Minecraft

1.20.1

### Relevant log output

```shell
https://pastebin.com/rVTeBT49
```

### Other Mods

```shell
List of mods is in crash log
```

**Comment by quiqueck** [comment] 2023-06-18 13:03
This is a duplicate of TerraformersMC/Biolith#4 and quiqueck/BetterNether#138.

**Closed as completed by quiqueck** 2023-06-18 13:03 UTC
Labels: 🥈 duplicate, 🚨 crash, 🧱 external

**Comment by Daihok41** [comment] 2023-06-18 17:36
Yea except im not using Biolith lol
