### ISSUE TITLE
[Bug] 1.19.3 results in server crash when generatng a world

### ISSUE THREAD

**Issue by AzureDoom** [quiqueck/BCLib#72] opened 2023-02-02 22:06 UTC
### What happened?

Start a 1.19.3 Fabric server with just BCLib enabled (Had already disabled BetterNether and BetterEnd as well as resetting the world). Server fails to start due to issue with datapack listed. 

Disabling it allows the world to create just normal. 

### BCLib

2.2.4

### Fabric API

0.73.2

### Fabric Loader

0.14.13

### Minecraft

1.19.3

### Relevant log output

```shell
[14:06:06] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (5ed172af)
[14:06:06] [main/INFO]: [bclib] Unable to build Biome List yet
[14:06:06] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[14:06:06] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[14:06:06] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[14:06:06] [main/INFO]: [bclib] Make sure features are loaded from terrablender
BCLib - The End  BiomeSource (5ed172af)
    biomes     = 0
    namespaces = 
    seed       = 0
    height     = 128
    deciders   = 0
    config     = BCLEndBiomeSourceConfig{mapVersion=hex, generatorVersion=paulevs, withVoidBiomes=true, innerVoidRadiusSquared=1048576, voidBiomesSize=256, centerBiomesSize=256, landBiomesSize=256, barrensBiomesSize=256}
[14:06:06] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (71d51d00)
[14:06:06] [main/INFO]: [bclib] Unable to build Biome List yet
[14:06:06] [main/INFO]: [bclib] Make sure features are loaded from terrablender
BCLib - Nether BiomeSource (71d51d00)
    biomes     = 0
    namespaces = 
    seed       = 0
    height     = 256
    config     = BCLibNetherBiomeSourceConfig{mapVersion=hex, useVerticalBiomes=true, amplified=true, biomeSize=256, biomeSizeVertical=128}
[14:06:06] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (79db3c1d)
[14:06:06] [main/INFO]: [bclib] Unable to build Biome List yet
[14:06:06] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[14:06:06] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[14:06:06] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[14:06:06] [main/INFO]: [bclib] Make sure features are loaded from terrablender
BCLib - The End  BiomeSource (79db3c1d)
    biomes     = 0
    namespaces = 
    seed       = 0
    height     = 128
    deciders   = 0
    config     = BCLEndBiomeSourceConfig{mapVersion=hex, generatorVersion=paulevs, withVoidBiomes=true, innerVoidRadiusSquared=1048576, voidBiomesSize=512, centerBiomesSize=256, landBiomesSize=1024, barrensBiomesSize=512}
[14:06:06] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (615a4ef8)
[14:06:06] [main/INFO]: [bclib] Unable to build Biome List yet
[14:06:06] [main/INFO]: [bclib] Make sure features are loaded from terrablender
BCLib - Nether BiomeSource (615a4ef8)
    biomes     = 0
    namespaces = 
    seed       = 0
    height     = 128
    config     = BCLibNetherBiomeSourceConfig{mapVersion=hex, useVerticalBiomes=true, amplified=false, biomeSize=1024, biomeSizeVertical=172}
[14:06:06] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (1942cace)
[14:06:06] [main/INFO]: [bclib] Unable to build Biome List yet
[14:06:06] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[14:06:06] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[14:06:06] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[14:06:06] [main/INFO]: [bclib] Make sure features are loaded from terrablender
BCLib - The End  BiomeSource (1942cace)
    biomes     = 0
    namespaces = 
    seed       = 0
    height     = 128
    deciders   = 0
    config     = BCLEndBiomeSourceConfig{mapVersion=square, generatorVersion=paulevs, withVoidBiomes=true, innerVoidRadiusSquared=1048576, voidBiomesSize=256, centerBiomesSize=256, landBiomesSize=256, barrensBiomesSize=256}
[14:06:06] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (1f4b95f3)
[14:06:06] [main/INFO]: [bclib] Unable to build Biome List yet
[14:06:06] [main/INFO]: [bclib] Make sure features are loaded from terrablender
BCLib - Nether BiomeSource (1f4b95f3)
    biomes     = 0
    namespaces = 
    seed       = 0
    height     = 128
    config     = BCLibNetherBiomeSourceConfig{mapVersion=square, useVerticalBiomes=true, amplified=false, biomeSize=256, biomeSizeVertical=86}
[14:06:06] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (4175cfd3)
[14:06:06] [main/INFO]: [bclib] Unable to build Biome List yet
[14:06:06] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[14:06:06] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[14:06:06] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[14:06:06] [main/INFO]: [bclib] Make sure features are loaded from terrablender
BCLib - The End  BiomeSource (4175cfd3)
    biomes     = 0
    namespaces = 
    seed       = 0
    height     = 128
    deciders   = 0
    config     = BCLEndBiomeSourceConfig{mapVersion=hex, generatorVersion=paulevs, withVoidBiomes=true, innerVoidRadiusSquared=1048576, voidBiomesSize=256, centerBiomesSize=256, landBiomesSize=256, barrensBiomesSize=256}
[14:06:06] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (9e88c6c)
[14:06:06] [main/INFO]: [bclib] Unable to build Biome List yet
[14:06:06] [main/INFO]: [bclib] Make sure features are loaded from terrablender
BCLib - Nether BiomeSource (9e88c6c)
    biomes     = 0
    namespaces = 
    seed       = 0
    height     = 128
    config     = BCLibNetherBiomeSourceConfig{mapVersion=hex, useVerticalBiomes=true, amplified=false, biomeSize=256, biomeSizeVertical=86}
[14:06:06] [main/WARN]: [bclib] No valid Biome Registry available!
[14:06:06] [main/INFO]: [worlds_together] Creating a new World, no fixes needed
[14:06:06] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5455.method_30530(net.minecraft.class_5321)" because "access" is null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:199) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.13.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5455.method_30530(net.minecraft.class_5321)" because "access" is null
	at org.betterx.worlds.together.worldPreset.WorldPresets.get(WorldPresets.java:35) ~[bclib-2.2.4.jar:?]
	at org.betterx.worlds.together.world.event.WorldBootstrap$Helpers.defaultServerPreset(WorldBootstrap.java:76) ~[bclib-2.2.4.jar:?]
	at org.betterx.worlds.together.world.event.WorldBootstrap$Helpers.defaultServerDimensions(WorldBootstrap.java:83) ~[bclib-2.2.4.jar:?]
	at org.betterx.worlds.together.world.event.WorldBootstrap$DedicatedServer.setupWorld(WorldBootstrap.java:122) ~[bclib-2.2.4.jar:?]
	at net.minecraft.server.Main.modify$zhl000$bcl_onCreate(Main.java:1033) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43613(Main.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:942) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:936) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:150) ~[server-intermediary.jar:?]
	... 4 more
```

### Other Mods

```shell
Modpack used: https://www.curseforge.com/minecraft/modpacks/uvision-fabric/files/4377304
```

**Comment by CloudTheWolf** [comment] 2023-02-23 10:40
Confirmed I get the same issue with version 2.2.4 and fabric version 0.14.14

[List of all mods](https://gist.github.com/CloudTheWolf/ff8a569bee1ba62a366b16d5ae1b8234)

**Comment by RakkenTi** [comment] 2023-02-23 13:33
Can also confirm, spent 1 hour trying to figure why only to see this right after opening the issue tracker...

**Comment by Nitjsefnie** [comment] 2023-03-07 20:51
I seem to have found a workaround, if you want to get a server with these mods and the new world gen, you need to create a world in singleplayer and use it as a world in your server

**Comment by tomcrusade** [comment] 2023-03-23 13:32
Or, in detail, you can do this, orderly:

1. generate world in server without bclib/betterx mods. 
2. Then, after the world generated, stop the server, then copy world seed
3. Generate end + nether in singleplayer with these betterx mods installed and obtained world seed
4. After that, copy pregenerated world into the server, plus betterx mods, then start the server. So far, it works

The caveat is that, if you want to generate new terrain (end + nether) in server, you have to generate it from singleplayer

**Comment by nimids** [comment] 2023-04-23 07:33
This is a duplicate of #68.

**Comment by E3VL** [comment] 2023-04-30 20:29
Also is happening on minecraft 1.19.2 bclib version 2.1.6

**Closed as completed** 2023-06-10 14:59 UTC
Labels: 🥈 duplicate
