### ISSUE TITLE
[Bug] Conflict with fabric API v0.56.0

### ISSUE THREAD

**Issue by Maxtar07** [quiqueck/BCLib#5] opened 2022-06-14 10:34 UTC
### What happened?

The server doesn't start when fabric API v0.56.0 is used with BCLib
It works well with v0.55.2 ans v0.55.3

### BCLib

2.0.4

### Fabric API

0.56.0

### Fabric Loader

0.14.7

### Minecraft

1.19

### Relevant log output

```shell
[12:27:25] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.7
[12:27:25] [main/INFO]: Loading 40 mods:
	- bclib 2.0.4
	- fabric 0.56.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.13+b2a4a624a9 via fabric
	- fabric-command-api-v1 1.2.5+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.1+cda9839ba9 via fabric
	- fabric-commands-v0 0.2.22+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.1.0+4a3ec384a9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.0.1+2a5b9210a9 via fabric
	- fabric-dimensions-v1 2.1.27+72da3b3da9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.23+9ff28f40a9 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.0.1+9e7660c6a9 via fabric
	- fabric-loot-tables-v1 1.1.1+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.8+33fbc738a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.5+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.16+92cf9a3ea9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.3+9e7660c6a9 via fabric
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.7
	- java 17
	- minecraft 1.19
[12:27:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/var/directory_serv/minecraft_297520/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[12:27:26] [main/INFO]: Compatibility level set to JAVA_17
[12:27:26] [main/WARN]: Error loading class: net/minecraft/class_5293 (java.lang.ClassNotFoundException: net/minecraft/class_5293)
[12:27:26] [main/WARN]: @Mixin target net.minecraft.class_5293 was not found bclib.mixins.common.json:PresetEditorMixin from mod bclib
[12:27:26] [main/WARN]: Error loading class: net/minecraft/class_7196 (java.lang.ClassNotFoundException: net/minecraft/class_7196)
[12:27:26] [main/WARN]: @Mixin target net.minecraft.class_7196 was not found bclib.mixins.common.json:WorldOpenFlowsMixin from mod bclib
[12:27:30] [main/INFO]: Building unoptimized datafixer
[12:27:31] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[12:27:31] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[12:27:31] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.7.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.7.jar:?]
	... 3 more
Caused by: java.lang.ClassCastException: class net.minecraft.class_5321 cannot be cast to class net.minecraft.class_6880 (net.minecraft.class_5321 and net.minecraft.class_6880 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5419f379)
	at net.fabricmc.fabric.impl.biome.TheEndBiomeData$RegistryKeyHashStrategy.equals(TheEndBiomeData.java:173) ~[fabric-biome-api-v1-9.0.13+b2a4a624a9-bc490388a6b05b0c.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenCustomHashMap.containsKey(Object2ObjectOpenCustomHashMap.java:399) ~[fastutil-8.5.6.jar:?]
	at net.fabricmc.fabric.impl.biome.TheEndBiomeData$Overrides.bcl_canGenerateAsEndBarrensBiome(TheEndBiomeData.java:543) ~[fabric-biome-api-v1-9.0.13+b2a4a624a9-bc490388a6b05b0c.jar:?]
	at org.betterx.bclib.interfaces.TheEndBiomeDataAccessor.bcl_canGenerateInEnd(TheEndBiomeDataAccessor.java:18) ~[bclib-2.0.4.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.lambda$getBiomes$6(BCLibEndBiomeSource.java:210) ~[bclib-2.0.4.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLBiomeSource.lambda$getBiomes$4(BCLBiomeSource.java:111) ~[bclib-2.0.4.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at org.betterx.bclib.api.v2.generator.BCLBiomeSource.getBiomes(BCLBiomeSource.java:113) ~[bclib-2.0.4.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.getBiomes(BCLibEndBiomeSource.java:205) ~[bclib-2.0.4.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.<init>(BCLibEndBiomeSource.java:82) ~[bclib-2.0.4.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.<init>(BCLibEndBiomeSource.java:78) ~[bclib-2.0.4.jar:?]
	at org.betterx.bclib.api.v2.levelgen.LevelGenUtil.getBCLEndLevelStem(LevelGenUtil.java:80) ~[bclib-2.0.4.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.createEndStem(BCLWorldPresetSettings.java:107) ~[bclib-2.0.4.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.buildDimensionMap(BCLWorldPresetSettings.java:85) ~[bclib-2.0.4.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.buildPreset(BCLWorldPresetSettings.java:71) ~[bclib-2.0.4.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresets.lambda$static$1(BCLWorldPresets.java:43) ~[bclib-2.0.4.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresets.bootstrapPresets(BCLWorldPresets.java:101) ~[bclib-2.0.4.jar:?]
	at net.minecraft.class_5317$class_7146.modify$zbi000$bcl_getOverworldStem(class_5317.java:571) ~[server-intermediary.jar:?]
	at net.minecraft.class_5317$class_7146.method_41600(class_5317.java:90) ~[server-intermediary.jar:?]
	at net.minecraft.class_5317.method_41593(class_5317.java:107) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.7.jar:?]
	... 3 more
```

**Comment by quiqueck** [comment] 2022-06-14 12:52
Duplicate of #4

**Closed as completed by quiqueck** 2022-06-14 12:52 UTC
Labels: 🥈 duplicate
