### ISSUE TITLE
[Bug] failed to start a server

### ISSUE THREAD

**Issue by galaxy-eye** [quiqueck/BCLib#82] opened 2023-03-13 15:06 UTC
### What happened?

A bug happened!
I can not start a server. But I can create a singleplayer world.

### BCLib

bclib 2.2.4

### Fabric API

fabric-api 0.75.1+1.19.3

### Fabric Loader

fabric-server-mc.1.19.3-loader.0.14.17-launcher.0.11.2

### Minecraft

1.19.3

### Relevant log output

```shell
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[23:01:56] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.17
[23:01:56] [main/INFO]: Loading 44 mods:
        - bclib 2.2.4
        - betterend 3.1.2
        - betternether 8.1.3
        - fabric-api 0.75.1+1.19.3
           |-- fabric-api-base 0.4.21+70be179c85
           |-- fabric-api-lookup-api-v1 1.6.20+49abcf7e85
           |-- fabric-biome-api-v1 12.1.1+b5d379b085
           |-- fabric-block-api-v1 1.0.5+e022e5d185
           |-- fabric-blockrenderlayer-v1 1.1.31+928d44d585
           |-- fabric-client-tags-api-v1 1.0.12+1134c5b885
           |-- fabric-command-api-v1 1.2.22+f71b366f85
           |-- fabric-command-api-v2 2.2.1+3fc4752e85
           |-- fabric-commands-v0 0.2.39+df3654b385
           |-- fabric-containers-v0 0.1.47+df3654b385
           |-- fabric-content-registries-v0 3.5.1+1d37d50285
           |-- fabric-convention-tags-v1 1.2.2+8e4e694f85
           |-- fabric-crash-report-info-v1 0.2.14+aeb40ebe85
           |-- fabric-data-generation-api-v1 11.3.1+40dc7a9485
           |-- fabric-dimensions-v1 2.1.42+00a2eb1085
           |-- fabric-entity-events-v1 1.5.7+b83334a085
           |-- fabric-events-interaction-v0 0.4.40+3baeb27a85
           |-- fabric-events-lifecycle-v0 0.2.44+df3654b385
           |-- fabric-game-rule-api-v1 1.0.30+99f9db8085
           |-- fabric-item-api-v1 2.1.10+312c329485
           |-- fabric-item-group-api-v1 2.1.12+1134c5b885
           |-- fabric-key-binding-api-v1 1.0.31+bc01e09785
           |-- fabric-keybindings-v0 0.2.29+df3654b385
           |-- fabric-lifecycle-events-v1 2.2.10+23a79c8a85
           |-- fabric-loot-api-v2 1.1.20+75e9821185
           |-- fabric-loot-tables-v1 1.1.24+9e7660c685
           |-- fabric-message-api-v1 5.1.0+c85585f885
           |-- fabric-mining-level-api-v1 2.1.31+49abcf7e85
           |-- fabric-models-v0 0.3.27+11ba9c3b85
           |-- fabric-networking-api-v1 1.2.17+4017a8cb85
           |-- fabric-networking-v0 0.3.34+df3654b385
           |-- fabric-object-builder-api-v1 5.4.1+eb2a3ba985
           |-- fabric-particles-v1 1.0.20+f1e4495b85
           |-- fabric-recipe-api-v1 1.0.1+5176f73d85
           |-- fabric-registry-sync-v0 2.1.0+f7b4d36485
           |-- fabric-renderer-api-v1 2.2.2+3a95925a85
           |-- fabric-renderer-indigo 0.8.0+3a95925a85
           |-- fabric-renderer-registries-v1 3.2.30+df3654b385
           |-- fabric-rendering-data-attachment-v1 0.3.25+afca2f3e85
           |-- fabric-rendering-fluids-v1 3.0.18+f1e4495b85
           |-- fabric-rendering-v0 1.1.33+df3654b385
           |-- fabric-rendering-v1 1.12.1+eb2a3ba985
           |-- fabric-resource-conditions-api-v1 2.3.0+e63306e085
           |-- fabric-resource-loader-v0 0.10.5+a91e48b785
           |-- fabric-screen-api-v1 1.0.41+f1e4495b85
           |-- fabric-screen-handler-api-v1 1.3.13+99f9db8085
           |-- fabric-sound-api-v1 1.0.8+75e9821185
           |-- fabric-transfer-api-v1 2.1.15+ccd377ba85
           \-- fabric-transitive-access-wideners-v1 2.3.1+40dc7a9485
        - fabricloader 0.14.17
        - java 17
        - minecraft 1.19.3
[23:01:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/admin/Desktop/mcserver/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[23:01:57] [main/INFO]: Compatibility level set to JAVA_17
[23:02:08] [main/INFO]: Building unoptimized datafixer
[23:02:12] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[23:02:13] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[23:02:13] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[23:02:13] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[23:02:13] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[23:02:13] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[23:02:13] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[23:02:13] [main/INFO]: [bclib] Added Config bclib.generator to auto sync (file hash)
[23:02:13] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[23:02:13] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[23:02:13] [main/INFO]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[23:02:15] [main/INFO]: [bclib] Added Config betterend.entities to auto sync (file hash)
[23:02:15] [main/INFO]: [bclib] Added Config betterend.blocks to auto sync (file hash)
[23:02:15] [main/INFO]: [bclib] Added Config betterend.items to auto sync (file hash)
[23:02:15] [main/INFO]: [bclib] Added Config betterend.biomes to auto sync (file hash)
[23:02:15] [main/INFO]: [bclib] Added Config betterend.recipes to auto sync (file hash)
[23:02:15] [main/INFO]: [bclib] Added Config betterend.enchantments to auto sync (file hash)
[23:02:37] [main/INFO]: [betternether] =^..^=    BetterNether for 1.19    =^..^=
[23:02:38] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:02:40] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (630f16ac)
[23:02:40] [main/INFO]: [bclib] Unable to build Biome List yet
[23:02:40] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[23:02:40] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[23:02:40] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[23:02:40] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (2d8bd18a)
[23:02:40] [main/INFO]: [bclib] Unable to build Biome List yet
[23:02:40] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (104af2f1)
[23:02:40] [main/INFO]: [bclib] Unable to build Biome List yet
[23:02:40] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[23:02:40] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[23:02:40] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[23:02:40] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (50d33c5a)
[23:02:40] [main/INFO]: [bclib] Unable to build Biome List yet
[23:02:41] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (19545b0c)
[23:02:41] [main/INFO]: [bclib] Unable to build Biome List yet
[23:02:41] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[23:02:41] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[23:02:41] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[23:02:41] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (29ade94b)
[23:02:41] [main/INFO]: [bclib] Unable to build Biome List yet
[23:02:41] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (4882bedc)
[23:02:41] [main/INFO]: [bclib] Unable to build Biome List yet
[23:02:41] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[23:02:41] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[23:02:41] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[23:02:41] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (a704916)
[23:02:41] [main/INFO]: [bclib] Unable to build Biome List yet
[23:02:41] [main/INFO]: [betternether] Freeze Registry[ResourceKey[minecraft:root / worlds_together:worldgen/betterx/surface_rules] (Stable)]
[23:02:41] [main/INFO]: [betternether] Freeze Registry[ResourceKey[minecraft:root / worlds_together:worldgen/betterx/surface_rules] (Stable)]
[23:02:41] [main/INFO]: [betternether] Freeze Registry[ResourceKey[minecraft:root / worlds_together:worldgen/betterx/surface_rules] (Stable)]
[23:02:41] [main/INFO]: [betternether] Freeze Registry[ResourceKey[minecraft:root / worlds_together:worldgen/betterx/surface_rules] (Stable)]
[23:02:41] [main/WARN]: [bclib] No valid Biome Registry available!
[23:02:41] [main/INFO]: [worlds_together] Creating a new World, no fixes needed
[23:02:41] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5455.method_30530(net.minecraft.class_5321)" because "access" is null
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:199) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.19.3-loader.0.14.17-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5455.method_30530(net.minecraft.class_5321)" because "access" is null
        at org.betterx.worlds.together.worldPreset.WorldPresets.get(WorldPresets.java:35) ~[bclib-2.2.4.jar:?]
        at org.betterx.worlds.together.world.event.WorldBootstrap$Helpers.defaultServerPreset(WorldBootstrap.java:76) ~[bclib-2.2.4.jar:?]
        at org.betterx.worlds.together.world.event.WorldBootstrap$Helpers.defaultServerDimensions(WorldBootstrap.java:83) ~[bclib-2.2.4.jar:?]
        at org.betterx.worlds.together.world.event.WorldBootstrap$DedicatedServer.setupWorld(WorldBootstrap.java:122) ~[bclib-2.2.4.jar:?]
        at net.minecraft.server.Main.modify$zzb000$bclib$bcl_onCreate(Main.java:533) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43613(Main.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_7237.method_42098(class_7237.java:42) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43612(Main.java:152) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:942) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:936) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:150) ~[server-intermediary.jar:?]
        ... 5 more
```

### Other Mods

```shell
- bclib 2.2.4
- betterend 3.1.2
- betternether 8.1.3
- fabric-api 0.75.1+1.19.3
```

**Comment by Evolution0** [comment] 2023-03-21 21:36
Can confirm, temporarily running without BCLib, BetterEnd, and BetterNether until its working serverside again.

**Comment by Nitjsefnie** [comment] 2023-03-23 14:24
Could someone close this as duplicate of https://github.com/quiqueck/BCLib/issues/72 ?

**Closed as completed** 2023-03-25 04:00 UTC
