### ISSUE TITLE
[Bug] errors in currently selected datapacks prevented world from loading

### ISSUE THREAD

**Issue by Cywym** [quiqueck/BCLib#116] opened 2023-07-11 01:45 UTC
### What happened?

My world was normal until i left it, after a while i downloaded some mods and this message pops up
![2023-07-10_22 09 47](https://github.com/quiqueck/BCLib/assets/94941744/59f2638f-872e-4506-ad67-357da468c1ab)
I created another world and the same thing happens, when i quit it and come back the message pops up
I decided to create a world without the Better x generation type and the message did no pop up and the world loaded as normal
Mod list:
![image](https://github.com/quiqueck/BCLib/assets/94941744/b32a3c12-e34b-41d1-bb35-f139ed44bbb5)
Log:
[latest.log](https://github.com/quiqueck/BCLib/files/12009875/latest.log)

### BCLib

3.0.11

### Fabric API

0.85.0

### Fabric Loader

0.14.21

### Minecraft

1.20.1

**Comment by quiqueck** [comment] 2023-07-12 08:36
Thank you for the report. This is a duplicate of #113, so Im closing this issue, but feel free to join the discussion over there...

**Closed as completed by quiqueck** 2023-07-12 08:36 UTC
Labels: 🥈 duplicate
