### ISSUE TITLE
[Bug] [1.20.1] BetterX World gen breaks custom biomes from other mods.

### ISSUE THREAD

**Issue by MbtMarco** [quiqueck/BCLib#131] opened 2023-09-26 14:51 UTC
Cinderscapes, Regions Unexplored and Incendium have problems in the generations of biomes or in the separation between one and the other (ex: Better Nether)

**Comment by Vexonek** [comment] 2023-10-09 17:54
Can confirm that issue, i used sinytra connector and pull that mod on forge and issue still remains. I used forge world gen mods like biomes o plenty so looks like this issue is caused by BClib and terrablender.

**Comment by quiqueck** [comment] 2023-12-20 14:30
I just tested this with my current development build on 1.20.1 (and the latest versions of Cinderscapes, Regions Unexplored and Incendium from Modrinth). The biomes appear to load just fine (suing the default BetterX World Type).

This is the result from the `/bclib print dimensions` command:
```
[bclib] World Dimensions: 
 - minecraft:the_end: 
     BCLib - Chunk Generator (654763e1) 
     BCLib - The End  BiomeSource (2dcb46b6)
         biomes     = 24
         namespaces = betterend(19), minecraft(5)
         seed       = 0
         height     = 128
         deciders   = 0
         config     = BCLEndBiomeSourceConfig{mapVersion=hex, generatorVersion=vanilla, withVoidBiomes=true, innerVoidRadiusSquared=1048576, voidBiomesSize=256, centerBiomesSize=256, landBiomesSize=256, barrensBiomesSize=256}
 - minecraft:overworld: 
     net.minecraft.class_3754@159ed1f2 
     class_4766 (33c51504)
         biomes     = 119
         namespaces = minecraft(53), regions_unexplored(66)
 - minecraft:the_nether: 
     BCLib - Chunk Generator (2ef7e455) 
     BCLib - Nether BiomeSource (31cc5a85)
         biomes     = 44
         namespaces = betternether(22), regions_unexplored(5), incendium(8), minecraft(5), cinderscapes(4)
         seed       = 0
         height     = 192
         config     = BCLibNetherBiomeSourceConfig{mapVersion=hex, useVerticalBiomes=true, amplified=false, biomeSize=256, biomeSizeVertical=86}
```

So it is either fixed in my latest build, or - if the issue still persists with the upcoming release of 3.0.14, I will need more information to reproduce the issue.

**Comment by ghost** [comment] 2023-12-26 14:08
Biomes itself generates but their surgace rules broken because of terrablender conflicts with betterx world type like it was mentioned in here https://github.com/quiqueck/BCLib/issues/75

**Comment by quiqueck** [comment] 2023-12-26 23:35
I just tested (with the latest released builds) 
<img width="966" alt="image" src="https://github.com/quiqueck/BCLib/assets/280847/48f3c00b-2a0e-47f6-824d-5d500b081611">

This looks like some surface rules were applied. Also tested for Incdendium Biomes, and they seem to generate surfaces as well... Do you still see this behaviour (it won't be fixed for existing chunks of course, but new worlds/chunks should generate fine...)

Oh and sorry if I miss the obvious and do not see the actual problem :D

**Comment by ghost** [comment] 2023-12-27 17:10
All works sorry for bothering, my problem was tied to connector.

**Comment by quiqueck** [comment] 2023-12-28 10:09
No bother :)

**Closed as completed** 2024-07-14 22:30 UTC
Labels: 💡 question
