### ISSUE TITLE
BCLib adds weird recepies.

### ISSUE THREAD

**Issue by Elkku6** [quiqueck/BCLib#30] opened 2022-08-01 17:37 UTC
BCLib 1.19 fabric adds weird recepies such as rails without iron. Bucket without anything.

**Comment by quiqueck** [comment] 2022-08-01 18:07
Since you did not specify the BCLib Version, I'll assume this is a duplicate of #29. Which was fixed with the just release 2.0.19 Update

**Closed as completed by quiqueck** 2022-08-01 18:07 UTC
