### ISSUE TITLE
Error on 1.19 server

### ISSUE THREAD

**Issue by V037** [quiqueck/BCLib#8] opened 2022-06-19 01:02 UTC
First error:
[02:47:42] [main/WARN]: Error loading class: net/minecraft/class_5293 (java.lang.ClassNotFoundException: net/minecraft/class_5293)
[02:47:42] [main/WARN]: @Mixin target net.minecraft.class_5293 was not found bclib.mixins.common.json:PresetEditorMixin from mod bclib
[02:47:42] [main/WARN]: Error loading class: net/minecraft/class_7196 (java.lang.ClassNotFoundException: net/minecraft/class_7196)
[02:47:42] [main/WARN]: @Mixin target net.minecraft.class_7196 was not found bclib.mixins.common.json:WorldOpenFlowsMixin from mod bclib

Second error:
[02:55:29] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5069ms or 101 ticks behind
[02:55:32] [Netty Server IO #1/ERROR]: Error receiving packet 93
java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@50301a74' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
        at net.minecraft.class_2540.method_42065(class_2540.java:147) ~[server-intermediary.jar:?]
        at net.minecraft.class_2767.method_11052(class_2767.java:47) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.76.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:213) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10761(class_2535.java:205) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.76.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-common-4.1.76.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.76.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.76.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.76.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[02:55:32] [VoiceChatPacketProcessingThread/INFO]: Successfully authenticated player ec139f6f-6cee-4080-b4c1-d6152b16080a
[02:55:33] [Server thread/INFO]: Vpower37 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@50301a74' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
[02:55:33] [Server thread/INFO]: Vpower37 left the game
[02:55:34] [Server thread/INFO]: Disconnecting client Vpower37

**Comment by quiqueck** [comment] 2022-06-30 06:59
The Mixin-Warnings should be fixed in the next release of BCLib (2.0.7). But as far as I can tell, they re not the cause for the crash. There seems to be a problem with `Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]`which is not related to the Mixin

**Comment by quiqueck** [comment] 2022-06-30 22:24
The warnings should be fixed 2.0.7. Please re-open this issue if you still have problems with the new release.

**Closed as completed by quiqueck** 2022-06-30 22:24 UTC
Labels: 🎉 Dev Code
