### ISSUE TITLE
[Bug] anvil not accepting equipment 

### ISSUE THREAD

**Issue by anshulg7** [quiqueck/BCLib#188] opened 2024-07-12 19:10 UTC
### What happened?

whenever I put an item in the anvil, the game crashes and returns this in the crash report

[crash-2024-07-12_14.53.41-client.txt](https://github.com/user-attachments/files/16198366/crash-2024-07-12_14.53.41-client.txt)

Minecraft version running 1.21

crash report:

### BCLib

21.0.5

### Fabric API

0.100.6

### Fabric Loader

0.15.11

### Minecraft

1.20.4

### Other Mods

```shell
vanilla, fabric, advancednetherite, armored-elytra, armorrestitched, balm-fabric, bclib, betterend, betternether, biolith, blur, cinderscapes, cinderscapes-client, cinderscapes-common, cinderscapes-worldgen, cloth-config, creativecore, enderitemod, endrem, entity_model_features, entity_texture_features, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fpsdisplay, friendsandfoes, gardens_of_the_dead, guardvillagers, idwtialsimmoedm, indium, iris, jei, lithium, medieval_buildings, mes, midnightlib, mns, mvs, reinfcore, reinfshulker, shield-disruptor, shield-disruptor-mc120, shulkerboxtooltip, simple-armor-hud, sodium, spectrelib, tectonic, terrablender, terraform-biome-remapper-api-v1, terraform-shapes-api-v1, terraform-surfaces-api-v1, terraform-wood-api-v1, veinmining, wover, wover-block, wover-core, wover-events, wover-generator, wover-preset, wover-surface, wover-ui, wunderlib, xaerominimap, xaeroworldmap
```

**Comment by OffsetMonkey538** [comment] 2024-07-13 05:41
Duplicate of #181

**Closed as completed** 2024-07-17 20:32 UTC
