### ISSUE TITLE
[Bug] "@Environment(EnvType.CLIENT)" line in the code causes the server to crash (this goes for better end as well) on fabric 0.15+

### ISSUE THREAD

**Issue by xg787** [quiqueck/BCLib#138] opened 2023-12-10 05:30 UTC
### What happened?

"@Environment(EnvType.CLIENT)" line in the code causes the server to crash (this goes for better end as well) on fabric 0.15+ and loads just fine without it in the code on server

### BCLib

any

### Fabric API

0.90.7

### Fabric Loader

0.15+

### Minecraft

1.20.1

**Comment by Mysterious-Wrangler** [comment] 2023-12-12 01:12
Anyone figure out a work around or something? Im trying to start a server but this is holding me back and who knows when it will get fixed.
Edit: fixed one of the crashes by building the jar from a fork, but better end is still not working unfortunately.

**Comment by liehr** [comment] 2023-12-18 14:49
Getting the same error here.

**Comment by Linguardium** [comment] 2023-12-20 04:46
duplicate of #136 and #137

**Comment by quiqueck** [comment] 2023-12-20 12:24
Duplicate of #136

**Closed as completed by quiqueck** 2023-12-20 12:24 UTC
Labels: 🥈 duplicate
