### ISSUE TITLE
[Bug] Logs are spammed with "Tried to read from global registry!" error.

### ISSUE THREAD

**Issue by SzczurekYT** [quiqueck/BCLib#92] opened 2023-05-03 18:04 UTC
### What happened?

Hello
When I join a world my log is spammed with "Tried to read from global registry!" error.
Due to the spam the logs files get really big in short timespan. On one playing sessions my latest.log file weighted over 1GB!

From

### BCLib

2.2.4

### Fabric API

0.75.1+1.19.3

### Fabric Loader

0.14.19

### Minecraft

1.19.3

### Relevant log output

```shell
Tried to read from global registry!
Tried to read from global registry!
Tried to read from global registry!
Tried to read from global registry!
Tried to read from global registry!
```

### Other Mods

```shell
BetterEnd 3.1.2 (no BetterNether)
Other mods in the comment (because github doesn't let me upload a screenshot)
```

**Comment by SzczurekYT** [comment] 2023-05-03 18:10
Other mods
(Most of them are from the [Additive](https://modrinth.com/modpack/additive) modpack. + Origins, BetterEnd and Bosses Of Mass Destruction with it's dependencies, Simple Voice Chat and few client side mods)
![image](https://user-images.githubusercontent.com/67533827/236005359-e4299175-1ce1-4946-9938-303f5b20cff3.png)

**Comment by quiqueck** [comment] 2023-05-16 12:43
Duplicate of #90

**Closed as completed** 2023-05-16 12:43 UTC
