### ISSUE TITLE
[Bug] BCLib does not generate config files.

### ISSUE THREAD

**Issue by byxea** [quiqueck/BCLib#187] opened 2024-07-09 15:38 UTC
### What happened?

I wanted to disable the fog handled by BCLib, so I unchecked Custom Fog Rendering, Render Fog in Nether denser, as well as set the Overall Fog Density to 0.0 with mod menu. 
The settings and changes apply, however upon exiting and relaunching Minecraft, the fog reappears and BCLib's settings are reset to default as the `config/bclib` folder always remains empty, and BCLib does not generate any config files. 

### BCLib

21.0.5

### Fabric API

0.100.6+1.21

### Fabric Loader

0.15.11

### Minecraft

1.21

### Relevant log output

Fabric log - [https://mclo.gs/wmScmZn](https://mclo.gs/wmScmZn)

### Mod List

1. **BCLib** [21.0.5]
2. **Fabric API** [0.100.6+1.21]
3. **Mod Menu** [11.0.1]
4. **Placeholder API** [2.4.0+1.21]
5. **WorldWeaver** [21.0.6]

**Comment by tennomai** [comment] 2024-07-10 08:25
Yep have the same problem it's really annoying.

**Comment by quiqueck** [comment] 2024-07-17 20:46
duplicate of #185

**Closed as completed by quiqueck** 2024-07-17 20:46 UTC
Labels: 🔥 bug, 🎉 Dev Code
